# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 899)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/battery.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTipDuration(-3)
        self.tabWidget.setStyleSheet("font: 11pt \"Calibri\";\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.frame_2)
        self.homeButton.setMinimumSize(QtCore.QSize(37, 0))
        self.homeButton.setMaximumSize(QtCore.QSize(102, 16777215))
        self.homeButton.setStyleSheet("")
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_3.addWidget(self.homeButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 0, 4, 1, 1)
        self.mergeBox = QtWidgets.QCheckBox(self.frame_2)
        self.mergeBox.setEnabled(False)
        self.mergeBox.setObjectName("mergeBox")
        self.gridLayout_3.addWidget(self.mergeBox, 0, 2, 1, 1)
        self.mergeButton = QtWidgets.QPushButton(self.frame_2)
        self.mergeButton.setMaximumSize(QtCore.QSize(142, 16777215))
        self.mergeButton.setObjectName("mergeButton")
        self.gridLayout_3.addWidget(self.mergeButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxFilter = QtWidgets.QGroupBox(self.frame)
        self.groupBoxFilter.setEnabled(True)
        self.groupBoxFilter.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight:bold;\n"
"color: rgb(0, 0, 0);")
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioBtnConductivity = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnConductivity.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnConductivity.setObjectName("radioBtnConductivity")
        self.gridLayout_2.addWidget(self.radioBtnConductivity, 0, 4, 1, 1)
        self.radioBtnCapacity = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnCapacity.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnCapacity.setObjectName("radioBtnCapacity")
        self.gridLayout_2.addWidget(self.radioBtnCapacity, 0, 1, 1, 1)
        self.radioBtnAll = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnAll.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnAll.setChecked(True)
        self.radioBtnAll.setObjectName("radioBtnAll")
        self.gridLayout_2.addWidget(self.radioBtnAll, 0, 0, 1, 1)
        self.radioBtnEnergy = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnEnergy.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnEnergy.setObjectName("radioBtnEnergy")
        self.gridLayout_2.addWidget(self.radioBtnEnergy, 0, 6, 1, 1)
        self.radioBtnCoulombic = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnCoulombic.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnCoulombic.setObjectName("radioBtnCoulombic")
        self.gridLayout_2.addWidget(self.radioBtnCoulombic, 0, 7, 1, 1)
        self.radioBtnVoltage = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnVoltage.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.radioBtnVoltage.setObjectName("radioBtnVoltage")
        self.gridLayout_2.addWidget(self.radioBtnVoltage, 0, 5, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxFilter)
        self.verticalLayout_2.addWidget(self.frame)
        self.groupBoxSearch = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBoxSearch.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxSearch.setFont(font)
        self.groupBoxSearch.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight:bold;\n"
"color: rgb(0, 0, 0);")
        self.groupBoxSearch.setObjectName("groupBoxSearch")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBoxSearch)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.searchInput = QtWidgets.QLineEdit(self.groupBoxSearch)
        self.searchInput.setEnabled(True)
        self.searchInput.setMaximumSize(QtCore.QSize(410, 16777215))
        self.searchInput.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.searchInput.setText("")
        self.searchInput.setDragEnabled(False)
        self.searchInput.setClearButtonEnabled(False)
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_9.addWidget(self.searchInput)
        self.searchClass = QtWidgets.QComboBox(self.groupBoxSearch)
        self.searchClass.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchClass.setFont(font)
        self.searchClass.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.searchClass.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.searchClass.setAcceptDrops(False)
        self.searchClass.setAutoFillBackground(False)
        self.searchClass.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.searchClass.setObjectName("searchClass")
        self.searchClass.addItem("")
        self.searchClass.addItem("")
        self.searchClass.addItem("")
        self.horizontalLayout_9.addWidget(self.searchClass)
        self.matchType = QtWidgets.QComboBox(self.groupBoxSearch)
        self.matchType.setStyleSheet("font: 11pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.matchType.setObjectName("matchType")
        self.matchType.addItem("")
        self.matchType.addItem("")
        self.horizontalLayout_9.addWidget(self.matchType)
        self.searchButton = QtWidgets.QPushButton(self.groupBoxSearch)
        self.searchButton.setMinimumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.searchButton.setStyleSheet("font: 11pt \"Calibri\";\n"
"font: bold;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);\n"
"background-color: rgb(85, 85, 255, 200);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon1)
        self.searchButton.setAutoDefault(False)
        self.searchButton.setDefault(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_9.addWidget(self.searchButton)
        self.verticalLayout_2.addWidget(self.groupBoxSearch)
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_2.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setStyleSheet("font: 11pt \"Calibri\";")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.dbEditUnit = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditUnit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbEditUnit.setObjectName("dbEditUnit")
        self.gridLayout.addWidget(self.dbEditUnit, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.dbEditRvalue = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditRvalue.setObjectName("dbEditRvalue")
        self.gridLayout.addWidget(self.dbEditRvalue, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.dbEditDOI_3 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.dbEditDOI_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dbEditDOI_3.setObjectName("dbEditDOI_3")
        self.gridLayout.addWidget(self.dbEditDOI_3, 16, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 18, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 15, 0, 1, 1)
        self.dbEditDOI_4 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.dbEditDOI_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dbEditDOI_4.setObjectName("dbEditDOI_4")
        self.gridLayout.addWidget(self.dbEditDOI_4, 15, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dbEditDOI = QtWidgets.QPlainTextEdit(self.groupBox)
        self.dbEditDOI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dbEditDOI.setObjectName("dbEditDOI")
        self.gridLayout.addWidget(self.dbEditDOI, 18, 1, 1, 1)
        self.dbEditValue = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditValue.setObjectName("dbEditValue")
        self.gridLayout.addWidget(self.dbEditValue, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 14, 0, 1, 1)
        self.dbEditDOI_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.dbEditDOI_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dbEditDOI_2.setObjectName("dbEditDOI_2")
        self.gridLayout.addWidget(self.dbEditDOI_2, 14, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 16, 0, 1, 1)
        self.dbEditRunit = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditRunit.setObjectName("dbEditRunit")
        self.gridLayout.addWidget(self.dbEditRunit, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.dbEditTag = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditTag.setObjectName("dbEditTag")
        self.gridLayout.addWidget(self.dbEditTag, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.dbEditName = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditName.setObjectName("dbEditName")
        self.gridLayout.addWidget(self.dbEditName, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.dbComboProperty = QtWidgets.QComboBox(self.groupBox)
        self.dbComboProperty.setEnabled(False)
        self.dbComboProperty.setObjectName("dbComboProperty")
        self.dbComboProperty.addItem("")
        self.dbComboProperty.addItem("")
        self.dbComboProperty.addItem("")
        self.dbComboProperty.addItem("")
        self.dbComboProperty.addItem("")
        self.gridLayout.addWidget(self.dbComboProperty, 0, 1, 1, 1)
        self.dbEditEname = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditEname.setObjectName("dbEditEname")
        self.gridLayout.addWidget(self.dbEditEname, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.dbEditSpecifier = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditSpecifier.setObjectName("dbEditSpecifier")
        self.gridLayout.addWidget(self.dbEditSpecifier, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.dbEditType = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditType.setObjectName("dbEditType")
        self.gridLayout.addWidget(self.dbEditType, 11, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 11, 0, 1, 1)
        self.dbEditWarning = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditWarning.setObjectName("dbEditWarning")
        self.gridLayout.addWidget(self.dbEditWarning, 12, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 0, 1, 1)
        self.dbEditInfo = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditInfo.setObjectName("dbEditInfo")
        self.gridLayout.addWidget(self.dbEditInfo, 13, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.splitter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/table.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.tab_6)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        self.frame_6.setEnabled(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnDrawPieChart = QtWidgets.QPushButton(self.frame_6)
        self.btnDrawPieChart.setEnabled(False)
        self.btnDrawPieChart.setMinimumSize(QtCore.QSize(61, 0))
        self.btnDrawPieChart.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);")
        self.btnDrawPieChart.setObjectName("btnDrawPieChart")
        self.horizontalLayout_8.addWidget(self.btnDrawPieChart)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.spinHoleSize = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.spinHoleSize.setEnabled(False)
        self.spinHoleSize.setMinimumSize(QtCore.QSize(70, 0))
        self.spinHoleSize.setDecimals(2)
        self.spinHoleSize.setMaximum(1.0)
        self.spinHoleSize.setSingleStep(0.1)
        self.spinHoleSize.setProperty("value", 0.2)
        self.spinHoleSize.setObjectName("spinHoleSize")
        self.horizontalLayout_8.addWidget(self.spinHoleSize)
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.spinPieSize = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.spinPieSize.setEnabled(False)
        self.spinPieSize.setMinimumSize(QtCore.QSize(70, 0))
        self.spinPieSize.setMaximum(1.0)
        self.spinPieSize.setSingleStep(0.1)
        self.spinPieSize.setProperty("value", 0.5)
        self.spinPieSize.setObjectName("spinPieSize")
        self.horizontalLayout_8.addWidget(self.spinPieSize)
        self.chkBox_PieLegend = QtWidgets.QCheckBox(self.frame_6)
        self.chkBox_PieLegend.setEnabled(False)
        self.chkBox_PieLegend.setChecked(True)
        self.chkBox_PieLegend.setObjectName("chkBox_PieLegend")
        self.horizontalLayout_8.addWidget(self.chkBox_PieLegend)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.widget_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.chartViewPie = QmyChartView(self.frame_7)
        self.chartViewPie.setObjectName("chartViewPie")
        self.horizontalLayout_12.addWidget(self.chartViewPie)
        self.splitter_4 = QtWidgets.QSplitter(self.frame_7)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.splitter_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_8)
        self.treeWidget_2.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.treeWidget_2.setFont(font)
        self.treeWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget_2.setAlternatingRowColors(True)
        self.treeWidget_2.setIndentation(0)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.header().setDefaultSectionSize(90)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.treeWidget_2)
        self.horizontalLayout_12.addWidget(self.splitter_4)
        self.verticalLayout_13.addWidget(self.frame_7)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/pie.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_6, icon3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.tab_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.widget_5)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.chartViewStackedBar = QmyChartView(self.frame_11)
        self.chartViewStackedBar.setObjectName("chartViewStackedBar")
        self.horizontalLayout_15.addWidget(self.chartViewStackedBar)
        self.splitter_6 = QtWidgets.QSplitter(self.frame_11)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.groupBox_10 = QtWidgets.QGroupBox(self.splitter_6)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.groupBoxSearch_2 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBoxSearch_2.setEnabled(True)
        self.groupBoxSearch_2.setObjectName("groupBoxSearch_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBoxSearch_2)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.searchInput_3 = QtWidgets.QLineEdit(self.groupBoxSearch_2)
        self.searchInput_3.setText("")
        self.searchInput_3.setObjectName("searchInput_3")
        self.horizontalLayout_6.addWidget(self.searchInput_3)
        self.searchButton_3 = QtWidgets.QPushButton(self.groupBoxSearch_2)
        self.searchButton_3.setEnabled(False)
        self.searchButton_3.setObjectName("searchButton_3")
        self.horizontalLayout_6.addWidget(self.searchButton_3)
        self.generateButton_3 = QtWidgets.QPushButton(self.groupBoxSearch_2)
        self.generateButton_3.setEnabled(False)
        self.generateButton_3.setObjectName("generateButton_3")
        self.horizontalLayout_6.addWidget(self.generateButton_3)
        self.clearButton_3 = QtWidgets.QPushButton(self.groupBoxSearch_2)
        self.clearButton_3.setEnabled(False)
        self.clearButton_3.setObjectName("clearButton_3")
        self.horizontalLayout_6.addWidget(self.clearButton_3)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBoxSearch_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.stackedWidget = QtWidgets.QTreeWidget(self.groupBox_10)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stackedWidget.setAlternatingRowColors(True)
        self.stackedWidget.setIndentation(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.header().setDefaultSectionSize(100)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.stackedWidget)
        self.horizontalLayout_15.addWidget(self.splitter_6)
        self.gridLayout_5.addWidget(self.frame_11, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_5, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.tab_4)
        self.frame_10.setEnabled(True)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnStackedBarH = QtWidgets.QPushButton(self.frame_10)
        self.btnStackedBarH.setEnabled(False)
        self.btnStackedBarH.setMinimumSize(QtCore.QSize(131, 0))
        self.btnStackedBarH.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);")
        self.btnStackedBarH.setObjectName("btnStackedBarH")
        self.horizontalLayout_10.addWidget(self.btnStackedBarH)
        self.btnStackedBar = QtWidgets.QPushButton(self.frame_10)
        self.btnStackedBar.setEnabled(False)
        self.btnStackedBar.setMinimumSize(QtCore.QSize(121, 0))
        self.btnStackedBar.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);")
        self.btnStackedBar.setObjectName("btnStackedBar")
        self.horizontalLayout_10.addWidget(self.btnStackedBar)
        self.zoominButton = QtWidgets.QPushButton(self.frame_10)
        self.zoominButton.setEnabled(False)
        self.zoominButton.setStyleSheet("")
        self.zoominButton.setObjectName("zoominButton")
        self.horizontalLayout_10.addWidget(self.zoominButton)
        self.zoomoutButton = QtWidgets.QPushButton(self.frame_10)
        self.zoomoutButton.setEnabled(False)
        self.zoomoutButton.setObjectName("zoomoutButton")
        self.horizontalLayout_10.addWidget(self.zoomoutButton)
        self.originalButton = QtWidgets.QPushButton(self.frame_10)
        self.originalButton.setEnabled(False)
        self.originalButton.setObjectName("originalButton")
        self.horizontalLayout_10.addWidget(self.originalButton)
        spacerItem2 = QtWidgets.QSpacerItem(523, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_7.addWidget(self.frame_10, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/bar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_4, icon4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setMinimumSize(QtCore.QSize(1041, 0))
        self.tab_7.setMaximumSize(QtCore.QSize(1041, 16777215))
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.tab_7)
        self.widget_2.setMinimumSize(QtCore.QSize(1041, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.widget_2)
        self.frame_4.setEnabled(True)
        self.frame_4.setMinimumSize(QtCore.QSize(1081, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(1081, 41))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 11, 0, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.histButton = QtWidgets.QPushButton(self.frame_4)
        self.histButton.setMinimumSize(QtCore.QSize(61, 0))
        self.histButton.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);")
        self.histButton.setObjectName("histButton")
        self.horizontalLayout_7.addWidget(self.histButton)
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.propertycomboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.propertycomboBox_2.setMinimumSize(QtCore.QSize(0, 31))
        self.propertycomboBox_2.setObjectName("propertycomboBox_2")
        self.propertycomboBox_2.addItem("")
        self.propertycomboBox_2.addItem("")
        self.propertycomboBox_2.addItem("")
        self.propertycomboBox_2.addItem("")
        self.propertycomboBox_2.addItem("")
        self.horizontalLayout_7.addWidget(self.propertycomboBox_2)
        self.gBoxHist_toolbar_2 = QtWidgets.QCheckBox(self.frame_4)
        self.gBoxHist_toolbar_2.setChecked(True)
        self.gBoxHist_toolbar_2.setObjectName("gBoxHist_toolbar_2")
        self.horizontalLayout_7.addWidget(self.gBoxHist_toolbar_2)
        spacerItem3 = QtWidgets.QSpacerItem(521, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 818, 818))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widgetHist_2 = QmyFigureCanvas(self.scrollAreaWidgetContents_3)
        self.widgetHist_2.setMinimumSize(QtCore.QSize(800, 800))
        self.widgetHist_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetHist_2.setObjectName("widgetHist_2")
        self.gridLayout_10.addWidget(self.widgetHist_2, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.verticalLayout_5.addWidget(self.widget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/histogram.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_7, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setEnabled(True)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 9, 0, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnVenn = QtWidgets.QPushButton(self.frame_3)
        self.btnVenn.setMinimumSize(QtCore.QSize(71, 0))
        self.btnVenn.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"selection-background-color: rgb(240, 240, 240);")
        self.btnVenn.setObjectName("btnVenn")
        self.horizontalLayout_5.addWidget(self.btnVenn)
        self.gBoxHist_toolbar_3 = QtWidgets.QCheckBox(self.frame_3)
        self.gBoxHist_toolbar_3.setChecked(True)
        self.gBoxHist_toolbar_3.setObjectName("gBoxHist_toolbar_3")
        self.horizontalLayout_5.addWidget(self.gBoxHist_toolbar_3)
        spacerItem4 = QtWidgets.QSpacerItem(662, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 918, 1318))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widgetVenn = QmyFigureCanvas(self.scrollAreaWidgetContents)
        self.widgetVenn.setMinimumSize(QtCore.QSize(900, 1300))
        self.widgetVenn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetVenn.setObjectName("widgetVenn")
        self.gridLayout_8.addWidget(self.widgetVenn, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_9.addWidget(self.widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/venn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_3, icon6, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/figure.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon7, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setStyleSheet("font: 11pt \"Calibri\";\n"
"background-color: rgb(255, 255, 255);")
        self.mainToolBar.setIconSize(QtCore.QSize(16, 16))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/logout.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon8)
        self.actQuit.setObjectName("actQuit")
        self.actRecAppend = QtWidgets.QAction(MainWindow)
        self.actRecAppend.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecAppend.setIcon(icon9)
        self.actRecAppend.setObjectName("actRecAppend")
        self.actRecInsert = QtWidgets.QAction(MainWindow)
        self.actRecInsert.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/insert.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecInsert.setIcon(icon10)
        self.actRecInsert.setObjectName("actRecInsert")
        self.actSubmit = QtWidgets.QAction(MainWindow)
        self.actSubmit.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/images/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSubmit.setIcon(icon11)
        self.actSubmit.setObjectName("actSubmit")
        self.actRevert = QtWidgets.QAction(MainWindow)
        self.actRevert.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/images/return.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRevert.setIcon(icon12)
        self.actRevert.setObjectName("actRevert")
        self.actRecDelete = QtWidgets.QAction(MainWindow)
        self.actRecDelete.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/images/cross.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecDelete.setIcon(icon13)
        self.actRecDelete.setObjectName("actRecDelete")
        self.actHelp = QtWidgets.QAction(MainWindow)
        self.actHelp.setCheckable(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/images/question.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon14.addPixmap(QtGui.QPixmap(":/icons/images/00.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actHelp.setIcon(icon14)
        self.actHelp.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actHelp.setObjectName("actHelp")
        self.mainToolBar.addAction(self.actRecAppend)
        self.mainToolBar.addAction(self.actRecInsert)
        self.mainToolBar.addAction(self.actRecDelete)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actSubmit)
        self.mainToolBar.addAction(self.actRevert)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actHelp)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)
        self.label_3.setBuddy(self.dbComboProperty)
        self.label_9.setBuddy(self.dbEditDOI)
        self.label_16.setBuddy(self.dbEditDOI)
        self.label_10.setBuddy(self.dbEditDOI)
        self.label_17.setBuddy(self.dbEditDOI)
        self.label_2.setBuddy(self.dbEditRunit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.searchClass.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Battery Database"))
        self.tabWidget.setStatusTip(_translate("MainWindow", "Database citation:  Huang, S., Cole, J.M. A database of battery materials auto-generated using ChemDataExtractor. Sci Data 7, 260 (2020). https://doi.org/10.1038/s41597-020-00602-2"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.mergeBox.setText(_translate("MainWindow", "Merged"))
        self.mergeButton.setText(_translate("MainWindow", "Show merged version"))
        self.groupBoxFilter.setTitle(_translate("MainWindow", "Data Types"))
        self.radioBtnConductivity.setText(_translate("MainWindow", "Conductivity"))
        self.radioBtnCapacity.setText(_translate("MainWindow", "Capacity"))
        self.radioBtnAll.setText(_translate("MainWindow", "All"))
        self.radioBtnEnergy.setText(_translate("MainWindow", "Energy"))
        self.radioBtnCoulombic.setText(_translate("MainWindow", "Coulombic Efficiency"))
        self.radioBtnVoltage.setText(_translate("MainWindow", "Voltage"))
        self.groupBoxSearch.setTitle(_translate("MainWindow", "Search"))
        self.searchClass.setItemText(0, _translate("MainWindow", "Name"))
        self.searchClass.setItemText(1, _translate("MainWindow", "DOI"))
        self.searchClass.setItemText(2, _translate("MainWindow", "Warning"))
        self.matchType.setItemText(1, _translate("MainWindow", "Generic Match"))
        self.matchType.setItemText(0, _translate("MainWindow", "Exact Match"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "Tag"))
        self.label_12.setText(_translate("MainWindow", "Unit"))
        self.label_3.setText(_translate("MainWindow", "Property"))
        self.label_9.setText(_translate("MainWindow", "Journal"))
        self.label_16.setText(_translate("MainWindow", "Published Date"))
        self.label.setText(_translate("MainWindow", "Value"))
        self.label_10.setText(_translate("MainWindow", "DOI"))
        self.label_17.setText(_translate("MainWindow", "Title"))
        self.label_2.setText(_translate("MainWindow", "Raw Unit"))
        self.label_8.setText(_translate("MainWindow", "Info"))
        self.label_5.setText(_translate("MainWindow", "Chemical Name"))
        self.label_7.setText(_translate("MainWindow", "Extracted Name"))
        self.dbComboProperty.setItemText(0, _translate("MainWindow", "Capacity"))
        self.dbComboProperty.setItemText(1, _translate("MainWindow", "Energy"))
        self.dbComboProperty.setItemText(2, _translate("MainWindow", "Conductivity"))
        self.dbComboProperty.setItemText(3, _translate("MainWindow", "Coulombic Efficiency"))
        self.dbComboProperty.setItemText(4, _translate("MainWindow", "Voltage"))
        self.label_6.setText(_translate("MainWindow", "Raw Value"))
        self.label_14.setText(_translate("MainWindow", "Specifier"))
        self.label_19.setText(_translate("MainWindow", "Type"))
        self.label_18.setText(_translate("MainWindow", "Warning"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Table"))
        self.btnDrawPieChart.setText(_translate("MainWindow", "Show"))
        self.label_13.setText(_translate("MainWindow", "HoleSize"))
        self.label_15.setText(_translate("MainWindow", "PieSize"))
        self.chkBox_PieLegend.setText(_translate("MainWindow", "Show Legend"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Data"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Property"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "Number of data records"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Capacity"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Conductivity"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("MainWindow", "Coulombic Efficiency"))
        self.treeWidget_2.topLevelItem(3).setText(0, _translate("MainWindow", "Energy"))
        self.treeWidget_2.topLevelItem(4).setText(0, _translate("MainWindow", "Voltage"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "PieChart"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Data"))
        self.groupBoxSearch_2.setTitle(_translate("MainWindow", "Input chemical names"))
        self.searchButton_3.setText(_translate("MainWindow", "Add"))
        self.generateButton_3.setText(_translate("MainWindow", "Generate Data"))
        self.clearButton_3.setText(_translate("MainWindow", "Clear"))
        self.stackedWidget.headerItem().setText(0, _translate("MainWindow", "Chemical Name"))
        self.stackedWidget.headerItem().setText(1, _translate("MainWindow", "Capacity"))
        self.stackedWidget.headerItem().setText(2, _translate("MainWindow", "Conductivity"))
        self.stackedWidget.headerItem().setText(3, _translate("MainWindow", "Coulombic Efficiency"))
        self.stackedWidget.headerItem().setText(4, _translate("MainWindow", "Energy"))
        self.stackedWidget.headerItem().setText(5, _translate("MainWindow", "Voltage"))
        self.btnStackedBarH.setText(_translate("MainWindow", "Show Horizontal"))
        self.btnStackedBar.setText(_translate("MainWindow", "Show Vertical"))
        self.zoominButton.setText(_translate("MainWindow", "Zoom in"))
        self.zoomoutButton.setText(_translate("MainWindow", "Zoom out"))
        self.originalButton.setText(_translate("MainWindow", "Original size"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "StackedBar"))
        self.histButton.setText(_translate("MainWindow", "Show"))
        self.label_11.setText(_translate("MainWindow", "Property Type"))
        self.propertycomboBox_2.setItemText(0, _translate("MainWindow", "Capacity"))
        self.propertycomboBox_2.setItemText(1, _translate("MainWindow", "Conductivity"))
        self.propertycomboBox_2.setItemText(2, _translate("MainWindow", "Coulombic Efficiency"))
        self.propertycomboBox_2.setItemText(3, _translate("MainWindow", "Energy"))
        self.propertycomboBox_2.setItemText(4, _translate("MainWindow", "Voltage"))
        self.gBoxHist_toolbar_2.setText(_translate("MainWindow", "Navigation Tool Bar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Histogram"))
        self.btnVenn.setText(_translate("MainWindow", "Show"))
        self.gBoxHist_toolbar_3.setText(_translate("MainWindow", "Navigation Tool Bar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "VennDiagram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Figure"))
        self.actQuit.setText(_translate("MainWindow", "Exit"))
        self.actQuit.setToolTip(_translate("MainWindow", "Quit"))
        self.actRecAppend.setText(_translate("MainWindow", "Add"))
        self.actRecAppend.setToolTip(_translate("MainWindow", "Add"))
        self.actRecInsert.setText(_translate("MainWindow", "Insert"))
        self.actRecInsert.setToolTip(_translate("MainWindow", "Insert"))
        self.actSubmit.setText(_translate("MainWindow", "Save"))
        self.actSubmit.setToolTip(_translate("MainWindow", "Save Changes"))
        self.actRevert.setText(_translate("MainWindow", "Cancel"))
        self.actRevert.setToolTip(_translate("MainWindow", "Cancel changes"))
        self.actRecDelete.setText(_translate("MainWindow", "Delete"))
        self.actRecDelete.setToolTip(_translate("MainWindow", "Delete records"))
        self.actHelp.setText(_translate("MainWindow", "Help"))
from myChartView import QmyChartView
from myFigureCanvas import QmyFigureCanvas
import res_rc
